name: youtube_mp3_download
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  youtube_explode_dart: ^1.9.4
  dio:

dev_dependencies:
  pedantic: ^1.9.0
